spring:
  config:
    import: optional:secret.yml
  data:
    mongodb:
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /service
#spring.data.mongodb.username=username
#spring.data.mongodb.password=password